BOT_NAME = 'book_covers_spider'

SPIDER_MODULES = ['backend.spiders']
NEWSPIDER_MODULE = 'backend.spiders'

ROBOTSTXT_OBEY = True
 
CONCURRENT_REQUESTS = 2
DOWNLOAD_DELAY = 2.0
RANDOMIZE_DOWNLOAD_DELAY = True
 
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 3600
 
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
 
LOG_LEVEL = 'INFO'
